server:
  port: 8081

spring:
  profiles:
    active: dev # 내 컴퓨터 도커연결

  jwt:
    secret: safetyas@$&!use;
  smtp:
    host: smtps.hiworks.com
    user: web@safety-as.com
    pwd: safetyas2018!*
  resources:
    static-locations: classpath:/css/
  thymeleaf:
    prefix: classpath:/templates/
    check-template: true
    check-template-location: true
    enabled: true
    suffix: .html
    mode: HTML