server:
  port: 8080

spring:
  profiles:
    active: dev # 내 컴퓨터 도커연결

  datasource:
    url: jdbc:mariadb://localhost:3306/soltsds
    driver-class-name: org.mariadb.jdbc.Driver
    username: soltsds
    password: soltsds

  jpa:
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: validate
    showSql: true
    properties:
      hibernate:
        format_sql: true
        format_use_sql_comments: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  jwt:
    secret: safetyas@$&!use;
  smtp:
    host: smtps.hiworks.com
    user: web@safety-as.com
    pwd: safetyas2018!*
  resources:
    static-locations: classpath:/css/
  thymeleaf:
    prefix: classpath:/templates/
    check-template: true
    check-template-location: true
    enabled: true
    suffix: .html
    mode: HTML
  file:
    path: C:\\PROJECT\\solt-sds\\upload\\

logging.level:
  org.hibernate.SQL: info
  org.hibernate.type: trace
